DROP TABLE IF EXISTS users;

CREATE TABLE users(
   id SERIAL PRIMARY KEY,
   username VARCHAR(255) NOT NULL,
   email VARCHAR(255) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL

);

DROP TABLE IF EXISTS recipes;

CREATE TABLE recipes(
   id SERIAL PRIMARY KEY,
   userId INTEGER,
   textarea TEXT NOT NULL,
   title VARCHAR(255),
   image VARCHAR(255)

);
